language: go

go:
  - release
  
before_install:
  
install:
  - go get -d code.google.com/p/go.tools/cmd/godoc

script:
  - find `go env GOROOT` -name doc.go -printf "%P\n" 
  - find `go env GOROOT`/../tip -name doc.go -printf "%P\n" 
